\clearpage
# DISCUSSION

Ce chapitre est divisé en trois sections. Dans la section \@ref(KeyConsiderations), nous examinons les principales considérations pour les trois priorités d’analyse qui ont façonné le travail présenté dans ce document : 1) production issue de la mise en valeur, 2) diversité des populations de saumon et 3) productivité variable dans le temps. Dans la section \@ref(KeyConclusions), nous présentons les principales conclusions tirées (1) des analyses géniteurs-recrues et (2) de la comparaison des approches de rechange pour l’élaboration de points de référence de gestion pour les regroupements. La section \@ref(PrioritiesFuture) traite des priorités pour les travaux futurs.


## PRINCIPALES CONSIDÉRATIONS {#KeyConsiderations}


Les principaux facteurs à prendre en considération pour l’élaboration d’objectifs de gestion pour les saumons rouges des rivières Skeena et Nass sont la forte proportion de poissons issus de la mise en valeur dans le regroupement de la rivière Skeena, le grand nombre de stocks ayant des dynamiques de production différentes dans chaque regroupement et la question de savoir comment réagir aux variations de la productivité dans le temps, qui sont de plus en plus fréquentes pour les stocks de saumon dans l’ensemble du Pacifique Nord.


###  Production issue de la mise en valeur

Les saumons rouges de la rivière Skeena issus de la mise en valeur représentent maintenant une grande proportion de la remonte totale de la rivière Skeena la plupart des années. De 1970 à 2020, les stocks mis en valeur (ruisseau Pinkut et rivière Fulton) constituaient en moyenne 67 % de la remonte totale de la rivière Skeena (fourchette de 33 à 83 %). Dans nos analyses, nous avons examiné séparément les stocks sauvages (autres que ceux du ruisseau Pinkut et de la rivière Fulton) et les stocks mis en valeur de la rivière Skeena, en mettant l’accent sur l’élaboration de points de référence biologiques au niveau du stock et au niveau du regroupement pour les stocks sauvages des rivières Skeena et Nass. Bien que les remontes totales de saumon rouge de la rivière Skeena aient considérablement augmenté depuis la mise en œuvre du PMVLB, les avantages réalisés pour les pêches ont été inférieurs aux prévisions (Hilborn 1992).

L’un des défis fondamentaux de la gestion du saumon rouge de la rivière Skeena est le compromis entre la réduction de la pêche ciblant des stocks mixtes pour protéger les plus petits stocks et l’augmentation de l’abondance de poissons excédentaires issus de la mise en valeur qui arrivent au lac Babine pour se trouver exclus des frayères. Les saumons rouges issus de la mise en valeur qui dépassent la capacité de fraie a diminué depuis 2000, mais ils représentent toujours une proportion importante de la remonte annuelle de la rivière Skeena (figure \@ref(fig:SurplusProduction)). L’excédent estimé en 2020 dépassait le nombre total de saumons rouges de la rivière Skeena récoltés dans toutes les pêches. Une partie de l’excédent peut être récoltée dans les pêches commerciales de poissons provenant du programme d’excédent de saumon par rapport aux besoins de géniteurs qui sont pratiquées dans le lac Babine, mais ces pêches n’ont pas lieu chaque année.

L’échappée de saumon rouge dans les frayères, le ruisseau Pinkut et la rivière Fulton a été relativement constante depuis le début du PMVLB, mais les remontes totales des stocks sauvages et mis en valeur du lac Babine (y compris les prises, l’échappée et la production excédentaire) et le nombre de recrues produites par géniteur ont diminué dans les dernières décennies, soulevant des préoccupations au sujet de la dépendance à la densité dans les milieux dulcicoles ou marins. La dépendance à la densité peut avoir une incidence sur la productivité à de multiples stades du cycle biologique dans les milieux dulcicoles et marins, et à différentes échelles. Certains effets peuvent être propres à un seul stock ou communs à de nombreux stocks dans une région. Par exemple, la capacité de croissance en eau douce dans le lac Babine régit la production de saumon rouge sauvage et mis en valeur du lac, tandis que la dépendance à la densité dans le milieu marin peut influencer le recrutement des stocks des rivières Skeena et Nass et d’autres stocks [@Peterman1982].

La taille des smolts du lac Babine a diminué constamment au fil du temps, les plus fortes diminutions ayant été observées dans les décennies précédant le PMVLB (annexe \@ref(ChannelReview)). La taille des smolts présente une corrélation positive avec la survie entre les stades du smolt et de l’adulte [@HendersonCass], et on a observé une survie selon la taille pour le saumon rouge du lac Babine [@WestLarkin]. Il existe une faible relation positive entre la survie entre les stades du smolt et de l’adulte et la longueur moyenne des smolts à la sortie du lac Babine, et une tendance à la baisse du poids des smolts avec l’augmentation de l’abondance, ce qui permet de penser que la dépendance à la densité en eau douce peut avoir une incidence sur la taille et la survie des smolts du lac Babine, mais nous n’avons pas suffisamment d’information pour l’évaluer au niveau du stock. Bien que des études antérieures aient conclu que la capacité de croissance dans le lac n’est pas un facteur limitatif pour le saumon rouge du lac Babine [@Shortreedetal2000PRModel], aucune étude limnologique actualisée n’a eu lieu depuis 2013 et aucune donnée n’a été publiée depuis 2000.

Les résultats du MBH confirment un effet annuel commun entre les stocks de saumon rouge de la rivière Skeena, ce qui donne à penser que les limitations du recrutement se produisent à l’échelle du regroupement. La covariation de la productivité se manifeste à des échelles régionales pour différentes espèces et populations de saumon du Pacifique dans tout le nord-est du Pacifique [p. ex. @PyperetalSpatialCov; @DorneretalCov]. Les déclins des populations de saumon rouge dans le nord-est du Pacifique ont été liés à l’abondance sans précédent de saumons du Pacifique qui grandissent actuellement dans le nord-est du Pacifique après des décennies de mise en valeur à grande échelle du saumon rose et du saumon kéta en provenance d’Asie et d’Amérique du Nord [@RuggeroneConnorsSxcomp].


Les stocks mis en valeur du lac Babine sont la composante la plus importante du saumon rouge de la rivière Skeena et un facteur clé de l’élaboration des objectifs de gestion. Bien que les stocks sauvages des rivières Skeena et Nass soient l’objet des analyses des points de référence biologiques présentées ici, les points de référence de gestion pour le saumon rouge de la rivière Skeena devront tenir compte de l’importante contribution du saumon rouge mis en valeur au regroupement. De 1970 à 2020, les stocks mis en valeur (ruisseau Pinkut et rivière Fulton) constituaient en moyenne 67 % de la remonte totale de la rivière Skeena (fourchette de 33 à 83 %). Étant donné que les cibles de charge pour les frayères et les tronçons gérés du ruisseau Pinkut et de la rivière Fulton sont établies de manière à obtenir des densités constantes de géniteurs qui sont maintenues afin de maximiser la production d’alevins, les modèles mathématiques géniteurs-recrues, comme le modèle de Ricker, qui ont besoin d’une fourchette d’échappées de géniteurs (c.-à-d. un contraste dans les données) ne produisent pas nécessairement des estimations de paramètres utiles. Pour les stocks dont l’échappée des géniteurs est fixe, les modèles géniteurs-recrues ne sont pas recommandés pour l’élaboration de points de référence biologiques ou d’objectifs de gestion pour les stocks mis en valeur. Bien que le comité d’examen du SCAS ait généralement reconnu les défis que pose la réalisation d’analyses géniteurs-recrues pour les stocks mis en valeur dont les données sur l’échappée des géniteurs sont peu contrastées, il a recommandé d’inclure les résultats de la modélisation géniteurs-recrues pour les stocks mis en valeur dans le présent document de recherche. Ces résultats sont présentés à l’annexe \@ref(PinkutFultonResults).

Nos analyses ont examiné séparément les saumons sauvages (autre que ceux du ruisseau Pinkut et de la rivière Fulton) de la rivière Skeena. Dans les sections \@ref(SpnEst) à \@ref(RunReconEst), nous avons résumé les méthodes d’estimation et les reconstitutions des remontes propres au saumon rouge du lac Babine, et évalué les tendances de la production excédentaire. Dans la section \@ref(SkeenaExpResults), nous avons examiné le ratio entre les saumons rouges sauvages et issus de la mise en valeur de la rivière Skeena afin d’élaborer un avis sur l’expansion des points de référence fondés sur l’abondance pour le regroupement de saumon sauvage de la rivière Skeena en tenant compte de la contribution de la mise en valeur.


### Diversité des populations de saumon

Les différents stocks des rivières Skeena et Nass examinés ici comprennent des dizaines d’UC distinctes qui frayent dans les affluents des deux bassins versants. Dans le cas du regroupement de la rivière Skeena, les saumons rouges autres que ceux du lac Babine, dont la remonte varie entre des centaines et des dizaines de milliers de géniteurs, représentent une proportion relativement faible de la remonte du regroupement, mais la majeure partie de sa diversité génétique. Du point de vue de la conservation, il est important de préserver le potentiel d’adaptation et d’évolution dans une métapopulation pour conserver la résilience aux changements environnementaux futurs [@Kardos2021GeneticVariation]. Dans une métapopulation, c’est une dynamique asynchrone des différentes populations qui confère la résilience et la stabilité des pêches associées [p. ex. @Hilborn2003Biocomplexity; @Schindleretal2010Portfolio], tandis qu’une dynamique plus synchrone des populations accroît la variabilité des remontes et des pêches [@Freshwateretal2015WeakenedPortfolio]. Dans le cas du regroupement de la rivière Skeena, la perte de biodiversité depuis le début de la pêche commerciale dirigée, caractérisée par une diminution des remontes de saumons rouges sauvages et une augmentation des proportions de saumons rouges issus du PMVLB, a été désignée comme une simplification du portefeuille [@Priceetal2021PortfolioSimpl].

Les variations génétiques existantes peuvent permettre aux populations de s’adapter plus rapidement aux changements environnementaux rapides [@Barrett2008]. Parmi les stocks de saumon rouge des rivières Skeena et Nass, il existe de nombreux exemples où la variation des caractéristiques des populations au niveau du stock est mesurable et contribue probablement à la dynamique asynchrone des populations entre les stocks. Ces populations présentent une diversité propre à chaque stock sur les plans des profils du cycle biologique, de la taille des smolts, de la période de montaison, de l’âge en eau douce et de l’âge à la montaison. La diversité de la structure selon l’âge en eau douce peut protéger une population contre les mauvaises conditions marines à différents stades du cycle biologique [@Moore2014LifeHistDiv]. La diversité de la période de montaison des adultes peut protéger certains stocks présentant des vulnérabilités différentes aux pêches à grande échelle, tandis que la diversité du cycle biologique et de la période de dévalaison des smolts peut atténuer les échecs d’une classe d’âge les années où la survie en mer est réduite [@Beamish2012] ou limiter le risque de non-concordance entre le moment de l’entrée en mer et la disponibilité des proies [i.e., @Satterthwaite2014; @CarrHarrisetal2018SmoltMigration].


Il est difficile de quantifier les liens directs entre les caractéristiques de la population et les avantages pour la conservation ou les pêches, mais il existe de nombreux exemples récents de variations des niveaux de population qui ont aidé à protéger les saumons rouges des rivières Skeena et Nass contre de faibles remontes. Dans la rivière Nass, la population de type océanique à montaison précoce représentait jusqu’à 30 % de la remonte du regroupement en 2018 et 2019, lorsque la remonte des stocks de la rivière Meziadin est tombée en deçà de son objectif d’échappée. Dans le complexe de stocks de la rivière Meziadin, une population reproductrice relativement nouvelle (ruisseau Strohn), qui est apparue au cours des dernières décennies, constitue maintenant une proportion importante de la remonte (M. Cleveland, Gitanyow Fisheries Authority, comm. pers. 2021). Dans le cas de la rivière Skeena, les remontes extrêmement faibles en 2013, 2017 et 2019, attribuables aux faibles remontes dans le ruisseau Pinkut et la rivière Fulton, ont été atténuées dans une certaine mesure par les remontes dans les réseaux de la rivière autres que ceux du lac Babine, qui représentaient jusqu’à 25 % de la remonte du regroupement, comparativement à seulement 10 % une année typique (données inédites du MPO).

Si l’on tient compte de l’abondance relative ou de l’uniformité des différentes populations, la diversité des saumons rouges des rivières Skeena et Nass a nettement diminué depuis le début des pêches commerciales dirigées à grande échelle au début du XXe siècle [@Priceetal2019Scales]. Pour de nombreuses populations de saumon rouge des rivières Skeena et Nass, l’histoire autochtone, les récits des premiers colons et les abondances historiques reconstituées récemment témoignent des remontes beaucoup plus importantes que les récentes séries chronologiques sur l’échappée pour ces stocks. Par exemple, le stock de la rivière Kitwanga, dont l’échappée dépassait probablement les dizaines de milliers au début du XXe siècle [@Priceetal2019Scales], a récemment connu des remontes aussi faibles que 230 géniteurs en 2018. Le saumon rouge de la rivière Kitwanga fait maintenant l’objet d’un effort de rétablissement intensif [@Cleveland2019KitwangaRecovery] et des plans de rétablissement ont été établis pour d’autres populations de la rivière Skeena qui ont été considérées comme préoccupantes sur le plan de la conservation à différents moments, y compris la population de la rivière Lakelse et celle de la rivière Morice.

Un objectif d’échappée pour le regroupement qui suppose une productivité moyenne à long terme et une composition stable des stocks pourrait ne pas protéger les populations moins productives contre la surexploitation. La réduction de la diversité et l’augmentation de la synchronie peuvent poser d’autres défis de gestion [@Freshwateretal2020Selectivity]. Le maintien de la diversité génétique des populations du regroupement peut protéger ces populations et les pêches qui en dépendent, et accroître leur résilience aux changements environnementaux [@Andersonetal2015Portfolio; @Kardos2021GeneticVariation].

La diversité des populations a été un élément clé de l’examen des objectifs d’échappée des saumons rouges des rivières Skeena et Nass, et elle a été désignée comme une priorité importante à aborder par le cadre de référence convenu bilatéralement, de même que par le GTT et les examinateurs indépendants. Certaines des approches de regroupement décrites à la section \@ref(AltApproachesComp), y compris les méthodes fondées sur l’état et la modélisation par simulation prospective, conviennent mieux que d’autres, comme l’estimation du rendement maximal durable au niveau du regroupement, pour intégrer la diversité au niveau du stock dans les objectifs de gestion. Le processus de consultation en cours sur la gestion a mis l’accent sur l’utilisation de la modélisation par simulation prospective, afin d’explorer les compromis entre les récoltes et les risques biologiques. Les résultats de la simulation peuvent renseigner sur les abondances des géniteurs qui sont associées au plus grand nombre de stocks atteignant les objectifs biologiques. Les simulations montrent que, dans le scénario de productivité récente, les prises atteindront un pic avec des objectifs de fraie pour le regroupement inférieurs à ceux qui maximiseraient le nombre de stocks sains.




### Productivité variable dans le temps {#ImportantTimeVar}

Les populations de saumon rouge évoluent rapidement en raison des effets cumulatifs des agents de stress, notamment la pression de la pêche et les changements climatiques. Les stocks des rivières Skeena et Nass ont connu une baisse de productivité, ainsi qu’une variabilité croissante et une fréquence accrue de faibles remontes depuis 2000. Les saumons rouges des rivières Skeena et Nass font maintenant partie d’une liste de plus en plus longue des principales populations de saumon rouge de la Colombie-Britannique (avec les saumons rouges des bras de mer Rivers et Smith et du fleuve Fraser), qui soutenaient autrefois les pêches commerciales canadiennes à grande échelle qui sont maintenant limitées par les faibles remontes et les efforts de conservation connexes. Les quatre remontes les plus faibles de saumon rouge de la rivière Nass ont été enregistrées de 2017 à 2022. Pour le saumon rouge de la rivière Skeena, les échappées les plus faibles depuis un glissement de terrain catastrophique dans la rivière Babine dans les années 1950 ont eu lieu en 2013, 2017 et 2019. 

Bien que les profils temporels de la variation de la productivité diffèrent selon le stock, une tendance générale au déclin est évidente dans l’ensemble des stocks.

* Profils des données géniteurs-recrues pour les stocks individuels ainsi que pour les regroupements des rivières Skeena et Nass (les géniteurs, les recrues observées par géniteur).
* Résiduels de Ricker (c.-à-d. la productivité observée comparée à la productivité prévue par les modèles ajustés).
* Baisse du paramètre de productivité (alpha) pour bon nombre des stocks pour lesquels il y a suffisamment de données pour ajuster les modèles de Ricker propres au stock avec une productivité variable dans le temps.
* Effet annuel commun constant dans les résultats du MBH pour l’ensemble des stocks de la rivière Skeena, constatation d’un profil à la baisse de la productivité semblable à celui observé pour l’ajustement du modèle de Ricker à un seul stock dans l’ensemble de données sur le regroupement de la rivière Skeena.

De plus, des signes montrent que la taille selon l’âge et la fécondité des saumons rouges des rivières Skeena et Nass ont diminué dans les dernières décennies. De façon anecdotique, des pêcheurs commerciaux qui ont longtemps ciblé le saumon rouge de la rivière Skeena ont signalé qu’ils avaient passé à des filets à mailles plus petites (de 5,5 à 4,75 po) à partir des années 1980. Au niveau de la population, des changements de la taille, de la composition selon l’âge ou de la taille selon l’âge ont été observés chez toutes les espèces de saumon dans différentes régions de l’Amérique du Nord [p. ex. @Oke2020RecentDeclinesBodySize; @Ohlbergeretal2020CkEscQual; @SchaulGeiger2016ClimateCoho]. Les profils de la diminution de la longueur totale et de la longueur selon l’âge pour les saumons rouges des rivières Skeena et Nass concordent avec les diminutions de même ampleur qui ont été observées chez les populations de saumon rouge du sud-est de l’Alaska [p. ex. @Oke2020RecentDeclinesBodySize].

Pour le saumon rouge de la rivière Skeena échantillonné dans la pêche d’essai à Tyee, la longueur selon l’âge a diminué de 2 ou 3 % pour les poissons d’âge 5, 6 et 7 et est demeurée constante pour les poissons d’âge 4 entre les années 1980 et les années 2010. La longueur totale des saumons rouges de la rivière Nass prélevés à la passe à poissons de la rivière Meziadin depuis 2010 est nettement plus petite que la moyenne historique, dénotant des changements dans la composition selon l’âge combinés à une diminution de la longueur des poissons échantillonnés. Les diminutions observées de la taille globale des populations échantillonnées des rivières Skeena et Nass, ainsi que les baisses observées d’environ 13 % de la fécondité des poissons échantillonnés dans les frayères de la rivière Babine, indiquent une tendance à la diminution de la reproduction, qui a des répercussions sur les populations sauvages et issues de la mise en valeur. Les objectifs d’échappée qui supposent une production d’œufs constante dans le temps ne tiennent pas toujours compte de ces profils du déclin de la qualité des échappées.

En plus des faibles remontes et des diminutions apparentes du potentiel reproductif, les saumons rouges des rivières Skeena et Nass font face à une augmentation de la fréquence des conditions environnementales extrêmes. Par exemple, le saumon rouge de la rivière Skeena de l’année d’éclosion 2013, elle-même la remonte la plus faible depuis les années qui ont immédiatement suivi le glissement de terrain dans la rivière Babine, a connu des conditions environnementales extrêmes tout au long de son cycle biologique. Les frayères n’ont pas atteint leurs cibles de charge en 2017, en 2017 et en 2019, et les smolts qui ont dévalé en mer en 2015 ont fait face à une vague de chaleur marine qui a persisté de 2014 à 2016, extrême de par son intensité, son étendue géographique et la profondeur inhabituelle des températures anormales [@Rossetal2021Heatwaves]. Les saumons rouges d’âge 4 et 5 qui sont remontés en 2017 et 2018 ont connu des conditions de sécheresse et des températures extrêmes pendant la montaison et dans les frayères. Bien que chacun de ces événements ait été propre au réseau hydrographique et constitue des exemples anecdotiques de ce qui était auparavant considéré comme des événements rares, il ne fait aucun doute que les événements extrêmes se produisent de plus en plus fréquemment.

Pour maintenir la santé et la diversité des populations de saumon rouge des rivières Skeena et Nass, il faudra planifier en fonction de ces événements extrêmes, notamment en élaborant des objectifs d’échappée et des stratégies de gestion qui peuvent s’adapter et réagir rapidement aux conditions changeantes, comme l’atténuation des températures extrêmes, comme on le fait pour le saumon rouge du fleuve Fraser [@FraserSKEnroute; @FraseSkMgmtAdjFAO2021]. Le maintien de la diversité des populations composant les regroupements aidera également à les protéger contre la probabilité d’événements catastrophiques futurs, dont il faudra tenir compte dans la gestion des pêches, y compris dans l’élaboration des objectifs d’échappée. Bien que les gestionnaires des pêches ne puissent pas prédire d’une année à l’autre des événements climatiques ou d’autres catastrophes, la probabilité de mauvais résultats peut être réduite en introduisant des tampons pour atténuer les risques et en maintenant la diversité au niveau du stock dans les métapopulations des rivières Skeena et Nass [@Andersonetal2015Portfolio].


L’une des principales constatations de l’examen des données était que de nombreux stocks de saumon rouge des rivières Skeena et Nass et les deux regroupements avaient une productivité de recrutement beaucoup plus faible ces dernières années que la moyenne à long terme. Nos analyses subséquentes ont porté sur l’exploration du rendement des stocks dans différents scénarios de productivité et ont en particulier comparé les résultats générés à l’aide des paramètres géniteurs-recrues élaborés en utilisant la productivité moyenne à long terme et la productivité récente (tableaux \@ref(tab:ProdCompTab2) et \@ref(tab:ProdCompBMRatioSmsy)). Les décideurs doivent tenir compte du fait que les productivités plus faibles se poursuivront probablement à l’avenir, mais nous avons inclus des résultats fondés sur la productivité moyenne à long terme pour illustrer le contraste et l’ampleur des différences selon diverses hypothèses de productivité. Il reste du travail à faire pour intégrer dans le cadre actuel différentes variations de la productivité, y compris différentes définitions de la productivité « récente ». Des travaux futurs possibles sur d’autres scénarios peuvent comprendre des considérations environnementales et limiter des avenirs probables en fonction des relations connues (on pourrait exploiter les différences entre les relations entre les stocks en fonction des travaux actuels ou en cours).


## PRINCIPALES CONCLUSIONS {#KeyConclusions}


### Autres ajustements du modèle géniteurs-recrues et scénarios de productivité

#### Autres formes du modèle géniteurs-recrues

Nous avons exploré trois formes de rechange du modèle géniteurs-recrues, ce qui a été instructif parce que (1) leur comparaison nous a aidés à comprendre les propriétés de chaque ensemble de données sur les géniteurs-recrues propre au stock et (2) les estimations des paramètres dans les différentes formes du modèle pourraient être utilisées à des fins différentes.
Dans le cas des stocks pour lesquels il existe des séries chronologiques complètes, lorsqu’il a été possible d’ajuster les trois formes du modèle géniteurs-recrues, les observations suivantes sont dignes de mention.

* Étant donné les fortes tendances temporelles des résiduels, l’ajustement du modèle de Ricker AR1 a amélioré les propriétés statistiques de l’ajustement par rapport à l’ajustement du modèle de Ricker de base. Nous avons donc choisi des paramètres de l’ajustement AR1 pour générer le scénario de productivité moyenne à long terme, le cas échéant.
* Les profils de productivité cernés à l’aide de l’ajustement du modèle avec PVT différaient entre les stocks et, dans certains cas, les profils de productivité suivaient de très près les résiduels de l’ajustement du modèle de Ricker de base (c.-à-d. qu’ils n’indiquaient pas de profil sous-jacent lisse). Ces profils de productivité très variables doivent être interprétés avec prudence, mais peuvent malgré tout être une source utile d’estimations des paramètres pour d’autres scénarios de productivité (c.‑à‑d. donner un contraste élevé avec les scénarios extrêmes de productivité élevée et faible). Par conséquent, nous avons utilisé les estimations des paramètres de productivité variable dans le temps pour différentes périodes afin de générer d’autres scénarios de productivité, le cas échéant. Les ajustements de la productivité variable dans le temps ont généralement donné des estimations plus incertaines du paramètre de productivité (des valeurs a posteriori plus larges de ln.alpha), mais des estimations plus précises de la capacité (des valeurs a posteriori plus étroites de Smax).


#### Points de référence biologiques


Le regroupement de saumon rouge de la rivière Nass comprend neuf UC différentes qui ont été combinées en sept stocks pour nos analyses, et celui de la rivière Skeena compte 30 UC existantes, qui ont été combinées en 24 stocks pour nos analyses. Des points de référence biologiques fondés sur la relation géniteurs-recrues ont été établis pour chacun des principaux stocks contributeurs des deux regroupements. La productivité des différents stocks des rivières Nass et Skeena varie au fil du temps, les stocks des regroupements et leurs principales composantes (stocks sauvages des rivières Meziadin et Babine) affichant des déclins quasi continus du nombre de recrues par géniteur, ainsi que du paramètre de productivité d’après les ajustements du modèle à un seul stock, depuis 2000 (figures \@ref(fig:FitsCompProd1) et \@ref(fig:FitsCompProd2)). D’autres scénarios plausibles de productivité ont été élaborés pour caractériser les scénarios de productivité élevée, faible, moyenne à long terme et récente en échantillonnant les distributions a posteriori pour le paramètre Ricker-alpha à partir des modèles disponibles les plus appropriés pour chaque scénario.

Des points de référence biologiques ont été estimés pour les différents stocks de saumon rouge des rivières Skeena et Nass à l’aide des distributions des paramètres générées par les scénarios de productivité de rechange. Nous les avons utilisés pour créer des illustrations des profils de probabilité d’équilibre et des points de référence pour les regroupements qui peuvent guider les choix d’objectifs d’échappée pour les regroupements, une fois que les objectifs de gestion auront été clairement définis.

Des essais approfondis ont montré que les estimations des points de référence pour certains stocks étaient très sensibles à un ou plusieurs des éléments suivants.


* *Traitement des données* (annexe \@ref(AltSRTest)) : L’exclusion des années d’éclosion où le nombre de recrues par géniteur est supérieur à 45 a fait une grande différence dans les estimations des points de référence pour certains stocks et nous considérons qu’il s’agit d’une étape nécessaire de contrôle de la qualité. Si elle donne des estimations très différentes des points de référence, cela indique qu’une ou deux valeurs extrêmes ont eu un effet important et devraient être examinées attentivement. En revanche, le remplissage des valeurs manquantes a généralement eu peu d’effet sur les estimations des points de référence, car nous avons utilisé des valeurs moyennes et le remplissage n’a pas généré de points extrêmes. Pour les stocks pour lesquels le remplissage a créé une différence dans l’estimation du modèle de Ricker de base, cela est dû à la structure selon l’âge. Une seule année manquante d’estimations des géniteurs et de la remonte peut exclure de trois à cinq années d’éclosion de l’ensemble de données sur les géniteurs-recrues. Par exemple, le remplissage de deux points de données de l’année de montaison pour la rivière Kitsumkalum a ajouté huit années d’éclosion à l’ensemble de données sur les géniteurs-recrues, mais n’a modifié la médiane de l’estimation de Srmd que de 6 %. Le remplissage de cinq points de données de l’année de montaison pour le stock de la rivière Asitka a plus que doublé les données sur les géniteurs-recrues accessibles, qui sont passées de 11 à 24 années d’éclosion, mais a également modifié considérablement les estimations qui en ont découlé (Srmd : -21 %, ln.alpha : -41%).
•	*Calculs des points de référence* (annexe  \@ref(BMCalcTest)) : Les estimations des points de référence biologiques étaient insensibles aux autres formulations (moins de 2 %), mais le taux de réussite variait pour les mises en œuvre de rechange de l’optimisateur de Sgen. Nous avons utilisé la méthode de @Scheuerell2016 pour calculer Srmd, car c’est la seule solution exacte, et la version de l’optimisateur de Sgen dans @Connorsetal2022, car c’était la seule méthode sans force brute qui n’a échoué pour aucune des combinaisons de paramètres testées.
* *Estimation bayésienne* : La médiane des estimations bayésiennes des points de référence dans les ajustements du modèle de Ricker de base était semblable aux estimations déterministes simples pour la plupart des stocks. Les stocks qui ont été signalés comme présentant plus de 25 % de différence avec l’estimation déterministe (figure \@ref(fig:FitsCompDetFig)) avaient également des estimations bayésiennes plus incertaines (c.-à-d. des valeurs a posteriori très larges) et étaient très sensibles aux autres valeurs a priori de la capacité (figure \@ref(fig:FitsCompCapPrior)).


Même si les estimations étaient généralement plus sensibles pour les petits stocks dont les données sur les géniteurs-recrues sont plus bruyantes et incomplètes que pour les grands stocks aux données de meilleure qualité, les différents tests de sensibilité n’ont pas toujours signalé les mêmes stocks. Les ajustements géniteurs-recrues pour les stocks mis en valeur et pour les données sur les géniteurs-recrues au niveau du regroupement, en particulier, étaient très sensibles aux autres hypothèses du modèle géniteurs-recrues, même si chaque estimation de géniteurs-recrues était de très bonne qualité.


#### Comparaison des ajustements du modèle pour un seul stock et pour les regroupements

Bien que le calcul des ajustements du modèle géniteurs-recrues pour les données des regroupements soit simple sur le plan informatique, les paramètres qui en résultent ne conviennent pas pour élaborer des objectifs de gestion.

Pour le regroupement de la rivière Skeena, la majorité des géniteurs efficaces et la plupart des adultes en montaison proviennent des installations du PMVLB du ruisseau Pinkut et de la rivière Fulton. Nous avons exploré les ajustements du modèle pour un regroupement SkeenaSauvage qui excluait les stocks mis en valeur, mais ce niveau d’analyse masquait la diversité des profils de productivité propres à chaque stock relevés dans les analyses au niveau du stock, en particulier le déclin important et récent de la productivité de plusieurs stocks sauvages de la rivière Skeena pour lesquels il existe des séries chronologiques complètes (ou complétées par remplissage). 

Pour le regroupement de la rivière Nass, deux stocks ayant des cycles biologiques et des dynamiques de production très différents expliquent la majeure partie de l’abondance. Par le passé, la remonte de la rivière Nass était principalement constituée de saumons rouges de type lacustre du lac Meziadin, mais ces dernières années, l’abondance absolue et la contribution relative des saumons rouges de type fluvial et océanique de la basse Nass ont augmenté. Nous estimons donc qu’il est plus approprié de modéliser ces deux stocks séparément, plutôt que dans un ensemble de données sur les géniteurs-recrues combinées.


#### Comparaison des ajustements du modèle géniteurs-recrues à un seul stock et hiérarchique

Au début de leur manuel WinBUGS, @WinBUGSManual rappellent ce qui suit aux utilisateurs, en caractères gras et en rouge : « *Attention! L’échantillonnage MCCM peut être dangereux.* » [traduction] La puissance informatique continue d’augmenter et les outils continuent d’évoluer (p. ex. de WinBUGS à JAGS à STAN), mais le défi de base demeure le même : si les estimations sont très sensibles à la structure du modèle et aux hypothèses sur les valeurs a priori, quelle version est la plus « correcte »?

Les tests de sensibilité approfondis sont une pratique courante dans l’estimation bayésienne. Cependant, dans le cadre de notre projet, nous avons eu la rare occasion de comparer deux mises en œuvre complètement distinctes et fondamentalement différentes du même type d’ajustement du modèle géniteurs-recrues exactement au même ensemble de données original. Des tests de sensibilité approfondis ont été menés pour les deux mises en œuvre du modèle, mais ce n’est qu’en comparant directement les deux mises en œuvre que nous avons pu déterminer les sources des écarts. La plupart des écarts initiaux importants dans les estimations des points de référence n’étaient pas attribuables à la structure hiérarchique, mais plutôt à d’autres spécifications de la valeur a priori de la capacité (Smax). Les différences étaient plus prononcées pour les stocks pour lesquels les données n’avaient pas de signal fort de la dépendance à la densité (un diagramme de dispersion « bruyant »), qui ont été signalés comme étant très sensibles dans les deux séries d’analyses.

La capacité de comparer des mises en œuvre indépendantes du modèle a servi de rappel important du fait que l’estimation bayésienne peut être très sensible aux hypothèses sur les valeurs a priori et aux différences structurelles. Les estimations qui en découlent doivent être vérifiées sur le terrain en fonction de l’expertise biologique, et l’incertitude propre au stock des estimations doit être prise en compte dans les utilisations subséquentes des résultats. 

Les conséquences des différences observées entre les estimations varieront selon la façon dont l’information est utilisée. Par exemple, si un processus décisionnel ultérieur se concentre sur la somme des estimations de Srmd au niveau du stock, de grandes différences relatives dans les estimations de Srmd pour quelques petits stocks n’auront alors pas d’effet important sur la décision. Cependant, si un processus décisionnel se concentre sur des évaluations de l’état qui intègrent des points de référence sur l’abondance relative, comme Sgen et 80 % de Srmd, de grandes différences dans les estimations des points de référence peuvent se traduire par un état global très différent, ce qui pourrait fortement influencer les décisions prises en fonction de ces évaluations.

De même, les profils estimés de la productivité par stock différaient entre les ajustements des modèles à un seul stock et hiérarchiques. Les deux ensembles de résultats peuvent être utiles et une comparaison directe est instructive. L’effet annuel commun dans le modèle hiérarchique recherche un profil commun entre les stocks et deux types de tests de sensibilité peuvent être utilisés pour étudier les profils estimés.

* *Descendant* : McAllister et Challenger (annexe \@ref(app:HBMFits)) ont commencé par une forme de modèle hiérarchique qui comprenait 18 stocks modélisés de la rivière Skeena, puis ont retiré un ou plusieurs stocks de l’analyse. Dans ces tests, l’effet annuel commun n’était pas sensible aux combinaisons de rechange de 16 ou 17 stocks.
* *Ascendant* : Une autre approche pourrait consister à commencer par ajuster des modèles hiérarchiques avec de plus petits groupes de stocks et à explorer comment l’effet annuel commun diffère pour ces plus petits groupes. Par exemple, nous avons pu tester les ajustements du modèle hiérarchique pour (1) seulement les trois stocks sauvages du lac Babine, (2) les cinq stocks du lac Babine, (3) tous les stocks sauvages de saumon rouge de type lacustre de la moyenne Skeena pour lesquels il existe des données sur les géniteurs-recrues, (4) tous les stocks de type lacustre de la basse Skeena pour lesquels il existe des données sur les géniteurs-recrues et (5) tous les stocks de type lacustre de la haute Skeena pour lesquels il existe des données sur les géniteurs-recrues. Sur la base de ces explorations, nous avons ensuite pu élaborer un modèle hiérarchique avec une structure spatiale plus nuancée.


### Approches de rechange afin d’élaborer des points de référence biologiques pour les regroupements{#AggregationComparison}

Ce document de recherche présente d’autres points de référence biologiques pour les stocks de saumon rouge des rivières Skeena et Nass, ainsi qu’un certain nombre d’approches différentes pour élaborer des points de référence pour les regroupements. Des choix précis quant à la façon d’utiliser l’information présentée ici, y compris les choix éventuels pour les objectifs d’échappée actualisés pour les saumons rouges des rivières Skeena et Nass, seront établis une fois que les objectifs de gestion auront été définis dans les processus suivants, y compris un processus d’évaluation multipartite pour sélectionner un objectif d’échappée pour les saumons rouges des rivières Skeena et Nass, qui est en cours.

Bien que différentes personnes participent à ces processus et que ceux-ci se dérouleront selon des échéanciers différents, ils reposent tous sur les mêmes renseignements fondamentaux : (1) des données géniteurs-recrues convenues, (2) une approche convenue d’ajustement du modèle géniteurs-recrues et (3) une approche convenue de calcul des points de référence biologiques qui en découlent. La façon dont les données, les ajustements du modèle et les points de référence biologiques sont pris en compte variera également d’un processus à l’autre. Nous nous sommes donc concentrés sur l’information fondamentale, mais nous avons aussi illustré comment elle pourrait être utilisée. Les approches présentées ici se veulent souples pour intégrer de nouveaux renseignements si le processus décisionnel l’exige; par exemple, on s’attend à ce que les ajustements du modèle et les points de référence biologiques changent lorsque les ensembles de données seront mis à jour à l’avenir. Les ensembles de données et les outils, ou les éléments de base, présentés ici, visent à fournir un point de départ pour le processus décisionnel, plutôt que des recommandations normatives pour les choix qui seront faits éventuellement.


#### Besoins pour l’examen des objectifs d’échappée

Des objectifs d’échappée révisés pour les saumons rouges des rivières Skeena et Nass sont requis pour la mise en œuvre des dispositions du TSP. À la suite de l’évaluation des approches de rechange par rapport aux critères de sélection élaborés par un groupe de participants à la réunion du SCAS, les travaux suivants ont porté sur l’élaboration d’une version améliorée du modèle de simulation prospective, ainsi que des profils de compromis d’équilibre pour évaluer les compromis pendant le processus de mobilisation sur la gestion.


* *Diagrammes de compromis d’équilibre* : Les profils de probabilité d’équilibre estiment le rendement prévu pour un stock donné dans différents scénarios de productivité. Par exemple, les profils d’équilibre pour le saumon rouge de la rivière Meziadin illustrent les probabilités d’atteindre 60 ou 80 % de la moyenne à long terme du rendement maximal durable ou un rendement d’équilibre supérieur à 100 000 géniteurs dans les scénarios de productivité moyenne à long terme ou récente (figure \@ref(fig:ProfileMezidian)). Ces résultats donnent à penser que le saumon rouge de la rivière Meziadin a très peu de chances d’atteindre l’un ou l’autre de ces objectifs dans les conditions actuelles.

* *Points de référence déterminés par simulation* : Des modèles de simulation peuvent être utilisés pour explorer les compromis entre les prises des regroupements et les risques biologiques pour les différentes populations de chaque réseau fluvial, dans une fourchette d’objectifs d’échappée pour le regroupement, ainsi que pour déterminer des objectifs de fraie pour le regroupement qui maximisent les prises, la santé du stock ou d’autres paramètres de rendement spécifiés. Pour la version initiale de ce document de recherche, nous avons élaboré un modèle de simulation simple pour illustrer le type de renseignements qui peuvent être intégrés à une évaluation de la stratégie de gestion. Le modèle de simulation a ensuite été peaufiné à la suite d’une discussion à la réunion d’examen par les pairs du SCAS et des recommandations de certains participants et examinateurs indépendants d’intégrer l’incertitude des résultats et la covariation dans la productivité. Ces modifications sont décrites à l’annexe \@ref(ModelExt).

Dans ce document, nous démontrons les avantages potentiels des simulations prospectives qui génèrent les trajectoires prévues selon d’autres hypothèses. L’une des principales constatations a été que les réponses aux différentes stratégies de récolte étaient très sensibles à l’hypothèse de la productivité. Il n’est pas surprenant que les abondances projetées soient plus faibles dans les scénarios de productivité récente que dans ceux de productivité moyenne à long terme pour la plupart des stocks de saumon rouge des rivières Skeena et Nass. La simulation a également permis de cerner des interactions contre-intuitives entre des scénarios de productivité et d’autres stratégies de récolte. Pour les objectifs d’échappée inférieurs aux objectifs d’échappée provisoires actuels, davantage de stocks atteignent l’objectif sur trois générations dans le scénario de productivité récente que dans le scénario de productivité moyenne à long terme. Dans le scénario de productivité moyenne à long terme, les remontes des regroupements sont plus importantes en raison des grands stocks productifs, et ces remontes se traduisent par un taux d’exploitation cible plus élevé, qui à son tour a une incidence sur les stocks moins productifs et plus petits (figures \@ref(fig:TradeoffPlotSkeenaWildLTAvg) à \@ref(fig:TradeoffPlotNassRecent)). 

Les extensions futures du modèle pourraient tenir compte d’autres considérations, comme les différences entre les zones et les périodes pour les répercussions sur la récolte, et la productivité future. De telles extensions doivent être soigneusement limitées afin de mettre l’accent sur les mécanismes pertinents pour les objectifs de l’analyse.


#### Besoins pour les initiatives régionales relatives au saumon

Les initiatives régionales relatives au saumon peuvent également s’appuyer sur les exemples d’autres approches de regroupement présentées ici.

* *Points de référence limites pour les regroupements* : De nouvelles directives [@LRPGuidelinesSAR] désignent deux des éléments de base présentés dans ce document de recherche comme des approches possibles pour l’élaboration des PRL en vertu de la *Loi sur les pêches* modernisée (2019). Plus précisément, les résultats de la régression logistique et l’illustration des évaluations de l’état à plusieurs critères incluses ici jettent les bases d’un processus officiel d’établissement des PRL pour les saumons rouges des rivières Skeena et Nass.

* *Évaluation de l’état à plusieurs critères* : Nous avons illustré les considérations relatives à l’état pour un seul paramètre, l’abondance par rapport aux points de référence biologiques (Sgen, 80 % de Srmd), mais les évaluations de l’état réel en vertu de la PSS reposent sur une combinaison de plusieurs critères (abondance absolue, tendances à long terme et à court terme, répartition). La réalisation d’évaluations de l’état à plusieurs critères pour les UC de saumon du Pacifique est un produit livrable clé de la mise en œuvre de la PSS.


## PRIORITÉS POUR LES TRAVAUX FUTURS {#PrioritiesFuture}

Dans le cadre du processus d’examen du SCAS qui a eu lieu en avril 2022, du processus de suivi sur la comparaison des approches de regroupement, des discussions avec les examinateurs indépendants et des commentaires fournis pendant le processus de consultation national en cours, nous avons cerné plusieurs domaines critiques pour les travaux futurs.

Chacune de ces tâches représente un travail considérable, tant sur le plan des analyses que du processus, et elles ne peuvent pas toutes être traitées en même temps, compte tenu de leur interdépendance et de la nécessité que les mêmes personnes contribuent à chacune ou presque. Par exemple :

* l’élaboration d’un PRL pour les regroupements conforme aux nouvelles lignes directrices exige des évaluations de l’état à plusieurs critères de chaque UC [@LRPGuidelinesSAR];
* il faudra élaborer un modèle de simulation amélioré et étendu pour étudier d’autres stratégies de gestion de l’excédent non reproducteur de saumon rouge issu de la mise en valeur;
* le même groupe de base d’employés du MPO devra participer de façon importante à ces deux analyses, en les réalisant tout en continuant de répondre aux besoins opérationnels annuels (p. ex. comités techniques de la Commission du saumon du Pacifique).

Nous attendons à ce que le processus de consultation national en cours et les discussions bilatérales entre le Canada et les États-Unis par l’entremise de la Commission du saumon du Pacifique fournissent les prochaines occasions d’élaborer des directives sur les priorités et la portée des prochaines phases des travaux. Nous résumons les tâches possibles ci-dessous pour faciliter les discussions sur la portée.



### Objectifs

Quelle que soit l’approche choisie pour élaborer les points de référence de gestion pour les regroupements de saumon rouge des rivières Skeena et Nass, l’application de cette approche exige des objectifs quantitatifs clairement définis. Nous avons utilisé divers exemples d’objectifs quantitatifs tout au long de ce document de recherche, mais le processus plus vaste d’examen des objectifs d’échappée doit permettre d’élaborer quatre types distincts d’objectifs convenus.

* *Objectifs quantitatifs pour les différents stocks sauvages* : Nous avons concentré nos analyses sur des objectifs simples au niveau du stock liés aux points de référence inférieur et supérieur de la PSS pour l’abondance relative (Sgen, 80 % de Srmd). Cependant, d’autres objectifs biologiques au niveau des stocks devraient être explorés et il faut définir des objectifs de récolte propres au stock, dans la mesure du possible (p. ex. pour certaines pêches en rivière).
* *Objectifs quantitatifs au niveau du regroupement* : Différents objectifs au niveau du regroupement sont implicitement ou explicitement requis pour appliquer d’autres approches d’élaboration des points de référence de gestion pour les regroupements. Plusieurs exigent une définition explicite de ce qui constitue la réussite pour chaque stock, puis une définition explicite de ce qui constitue la réussite pour le regroupement. En mettant l’accent sur les stocks sauvages seulement, nous avons utilisé l’exemple suivant : « *Au moins 80 % des stocks du regroupement devraient avoir une probabilité d’au moins 80 % que l’abondance des géniteurs dépasse le point de référence supérieur de la PSS pour le paramètre d’abondance relative (80 % de Srmd dans le scénario de productivité moyenne à long terme) après trois générations (années de simulation 11 à 15)* ». Cependant, de nombreuses variantes d’objectifs comme celui-ci pourraient être envisagées et mises à l’essai, et il faudrait dresser une liste restreinte convenue.
* *Objectifs quantitatifs pour les différents stocks mis en valeur* : Les activités du PMVLB sont actuellement gérées selon l’objectif général de maximiser la production de smolts dans des conditions historiques, mais cet objectif général devrait être revu compte tenu des changements observés dans l’environnement, dans les stocks sauvages et dans la dynamique des populations des stocks mis en valeur.
* *Objectifs quantitatifs pour le regroupement de la rivière Skeena, comprenant les stocks sauvages et mis en valeur* : À l’heure actuelle, il n’existe aucune directive stratégique explicite concernant l’équilibre souhaité entre les objectifs biologiques pour les stocks sauvages, les objectifs de production pour les stocks mis en valeur, les objectifs de récolte pour les remontes combinées de stocks sauvages et mis en valeur, ainsi que l’excédent non récolté et non reproducteur des remontes de stocks mis en valeur. Une évaluation officielle de la stratégie de gestion, combinant un modèle de simulation et un processus participatif structuré, offre un cadre complet pour définir les objectifs généraux et les mécanismes clés, construire un modèle de simulation personnalisé pour tester d’autres scénarios et peaufiner les analyses et les objectifs au fil du temps.

### Données

Le système naturel et social dans lequel nous essayons collectivement de gérer les saumons rouges des rivières Skeena et Nass évolue rapidement et les programmes d’évaluation annuelle s’adaptent aux changements qui interviennent dans les stocks, les pêches et les outils accessibles. De ce fait, la base de données accessibles pour l’examen des objectifs d’échappée des saumons rouges des rivières Skeena et Nass évolue constamment, ce qui a une incidence sur les priorités des analyses et du processus. Par exemple, l’identification émergente des stocks fondée sur l’ADN pourrait fournir de meilleures estimations des répercussions de la récolte par stock. De même, de nouveaux renseignements sont en cours d’élaboration au sujet des méthodes les plus appropriées pour estimer les échappées de géniteurs pour deux stocks (rivières Bowser et Bear).

Les analyses présentées dans ce document de recherche ont utilisé les données sur les géniteurs-recrues jusqu’aux remontes de 2019, après un examen approfondi des données sources [@SkeenaNassSkDataRep]. Les remontes de 2020, 2021 et 2022, qui ne sont pas intégrées dans l’analyse actuelle, étaient inhabituelles pour bon nombre des stocks et pourraient avoir une incidence importante sur les estimations des paramètres. À mesure que les données seront mises à jour et que les estimations des paramètres géniteurs-recrues seront revues, les valeurs précises des points de référence biologiques et les résultats de l’approche de regroupement choisie changeront également. Cependant, les mises à jour régulières des reconstitutions des remontes, des ajustements géniteurs-recrues, des évaluations de l’état et des reprises des simulations constituent une tâche importante. La planification des mises à jour régulières doit intégrer cette tâche dans le contexte de toutes les tâches prioritaires.

### Modélisation des géniteurs-recrues et scénarios de productivité

Les analyses des géniteurs-recrues présentées ici comprennent des tests de sensibilité approfondis (trois formes du modèle à un seul stock, quatre autres valeurs a priori de la capacité, des traitements de données de rechange, d’autres approches d’estimation des points de référence, des ajustements du modèle à un seul stock ou du MBH). Les discussions qui ont eu lieu durant le processus d’examen par les pairs ont permis de cerner plusieurs domaines à explorer davantage.

* *Autres valeurs a priori de la capacité* : Nous avons testé quatre combinaisons avec des distributions uniformes ou log-normales et des bornes larges ou plafonnées de la distribution. Les bornes ont été choisies en fonction des renseignements disponibles pour chaque stock, y compris les estimations de la capacité des lacs fondées sur le rendement photosynthétique, la plus grande abondance observée des géniteurs et les distributions a posteriori bayésiennes d’une première série d’ajustements du modèle géniteurs-recrues. On pourrait tester d’autres mises en œuvre de la valeur a priori de la capacité log-normale et d’autres bornes de la valeur a priori de la capacité afin d’explorer davantage la sensibilité des estimations des paramètres géniteurs-recrues obtenus pour les stocks dont les estimations de la capacité sont très incertaines. Ce point a été désigné comme une priorité, car d’importantes différences initiales entre les ajustements du modèle à un seul stock et le MBH ont été attribuées aux différences dans la façon dont les valeurs a priori de la capacité ont été établies.
* *Simulations stochastiques du biais* : Des biais potentiels dans les estimations des paramètres géniteurs-recrues pourraient découler de différents détails de la mise en œuvre (p. ex. traitement des données, formes du modèle, valeurs a priori de la capacité, mise en œuvre MCCM bayésienne). Nous avons effectué des tests de sensibilité approfondis, mais une exploration plus formelle des biais potentiels pourrait générer de nombreux ensembles de données aléatoires pour des stocks hypothétiques à la dynamique des populations connue, conçus pour être semblables aux différents stocks de saumon rouge des rivières Skeena et Nass, puis appliquer d’autres variations de l’ajustement du modèle géniteurs-recrues pour vérifier quelle version produit les estimations les plus similaires aux valeurs « réelles ».
* *Changement de forme du modèle* : Pour les stocks dont les ensembles de données sur les géniteurs-recrues sont complets (pas d’années manquantes), la mise en œuvre actuelle d’autres scénarios de productivité a échantillonné des paramètres de l’ajustement du modèle de Ricker AR1 pour le scénario de productivité moyenne à long terme et de la plus récente génération de l’ajustement du modèle de Ricker avec PVT pour le scénario de productivité récente. Certains participants à l’examen par les pairs étaient préoccupés par les conséquences possibles de l’utilisation de différentes formes du modèle pour les scénarios de productivité. D’autres versions du scénario de productivité moyenne à long terme, fondées sur l’ajustement du modèle avec PVT, pourraient être explorées (p. ex. échantillonner toutes les années d’éclosion plutôt que seulement les générations les plus récentes, ou calculer la moyenne de ln.alpha pour les années d’éclosion pour chaque ensemble de paramètres MCCM).
* *Autre structure hiérarchique pour l’ajustement du MBH* : Comme nous l’avons vu à la section \@ref(KeyConclusions) ci-dessus, différentes hypothèses au sujet de la structure hiérarchique du saumon rouge de la rivière Skeena pourraient être mises à l’essai dans le cadre d’estimation élaboré par McAllister et Challenger (annexe  \@ref(app:HBMFits)).

### Stocks mis en valeur du Ruisseau Pinkut et de la rivière Fulton

Les priorités pour les travaux futurs ont trait à l’évaluation des stocks, à la gestion des frayères, aux interactions avec les stocks sauvages et aux approches de rechange pour élaborer une stratégie de récolte combinée des stocks sauvages et mis en valeur. Plus précisément, les tâches sont les suivantes.

* *Examen des cibles de charge des frayères* : Nous avons inclus dans ce rapport un aperçu des données et des tendances sur la production d’œufs, d’alevins et de smolts. Une analyse approfondie de la production issue de la mise en valeur de saumon rouge du lac Babine, qui s’inscrit dans un examen plus vaste de l’efficacité des écloseries de saumon dans la région du Pacifique, dirigé par la Fondation du saumon du Pacifique, est en cours (Cam West, comm. pers., Programme de mise en valeur des salmonidés du MPO [retraité] 2021). Toutefois, ce travail ne porte que sur les éléments techniques de la production des frayères, en mettant l’accent sur les saumons rouges issus de la mise en valeur du lac Babine. Un examen intégré plus vaste est nécessaire pour déterminer comment la gestion des frayères devrait réagir à ces changements biologiques observés. 
* *Étudier les interactions biologiques entre les populations mises en valeur et sauvages* : Bien que les données sur la production d’œufs, d’alevins et de smolts pour le lac Babine suggèrent une dépendance à la densité en eau douce, avec des réductions de la taille des smolts associées à une production accrue d’alevins, il reste encore du travail à faire pour comprendre les effets à long terme du PMVLB sur les populations sauvages du lac et d’autres populations de saumon rouge de la rivière Skeena, notamment de l’information à jour sur les changements dans la capacité de croissance en eau douce pour le lac Babine, et une analyse détaillée de survie en mer en fonction de la taille, ainsi que du recrutement dans un éventail de conditions océaniques. Une meilleure résolution génétique entre les différents stocks du lac Babine pourrait aider à mieux comprendre le potentiel d’errance entre les populations.    
* *Étudier les interactions indirectes entre les populations mises en valeur et les populations sauvages au moyen de l’abondance du regroupement, des règles de récolte pour le regroupement et des pêches ciblant des stocks mixtes* : Il faudrait probablement un modèle de simulation étendu avec une composante distincte pour la dynamique des populations des stocks mis en valeur et une résolution plus fine de la récolte simulée (p. ex. différentes récoltes des stocks sauvages et mis en valeur en fonction de la période, de l’emplacement et de l’engin de pêche).
* *Examen de la gestion de l’excédent* : Nos analyses des géniteurs-recrues et les éléments de base qui en découlent pour les points de référence de gestion des regroupements étaient axés sur les stocks sauvages. Cependant, la gestion de la récolte de saumon rouge de la rivière Skeena doit trouver un équilibre entre les considérations relatives aux stocks sauvages, les considérations opérationnelles pour les stocks mis en valeur et l’interaction entre l’excédent biologique des stocks issus des frayères artificielles avec des taux de récolte des regroupements sur les remontes combinées des stocks sauvages et des stocks mis en valeur. Ces défis, qui ne sont pas nouveaux pour la gestion des pêches ciblant le saumon rouge de la rivière Skeena, se posent indépendamment de l’approche choisie pour établir les objectifs pour le regroupement (p. ex. profils de probabilité par rapport à la simulation prospective).


### Intégration des considérations biologiques dans les points de référence de gestion pour les regroupements

La productivité changeante a été désignée comme la première priorité d’analyse par les participants à l’atelier d’établissement de la portée, les membres du GTT et les examinateurs indépendants pour l’examen des objectifs d’échappée pour les saumons rouges des rivières Skeena et Nass. Nous présentons ici une approche pour sélectionner les paramètres du modèle géniteurs-recrues qui décrivent d’autres scénarios de productivité, et nous en montrons les conséquences pour les estimations qui en découlent des points de référence biologiques et toutes les considérations fondées sur ces points de référence. L’importance de tenir compte de la productivité variable dans le temps est abordée à la section \@ref(ImportantTimeVar)  ci-dessus. En particulier, les priorités pour les travaux futurs sont les suivantes.


* *Détermination des régimes de productivité* : Nos analyses comprenaient une approche pour produire d’autres scénarios de productivité (productivité moyenne à long terme par rapport à récente), mais nous n’avons pas analysé les tendances temporelles observées de la productivité pour chercher des preuves de changements discrets de la productivité (régimes). Des analyses comme celles de @Rodionov2005Regimes  peuvent déterminer les régimes de productivité changeants et aider à limiter des scénarios de productivité futurs (p. ex. pour la simulation prospective).
* *Directives pour la prise en compte des changements de productivité dans les points de référence biologiques et de gestion* : La détermination des changements passés de la productivité est une étape importante, mais l’intégration de cette information dans un contexte de gestion présente de nombreux défis conceptuels. Par exemple, si la productivité récente est inférieure à la moyenne, les estimations de Srmd selon une hypothèse de productivité récente seront généralement également plus basses. Faudrait-il abaisser les objectifs d’échappée les années de faible productivité, les laisser inchangés pour éviter de réduire l’abondance à long terme ou les augmenter pour accélérer la reconstitution? Une initiative de recherche pluriannuelle a été lancée à l’été 2022 afin d’élaborer des directives formelles pour les considérations de gestion dans le contexte d’une productivité changeante (Carrie Holt et Brendan Connors, comm. pers., MPO 2022).
* *Intégration des changements démographiques aux objectifs d’échappée* : Pour les populations dont la qualité des échappées subit des changements, comme une réduction de la taille, de la fécondité ou du sex ratio, les objectifs d’échappée qui supposent une production d’œufs constante peuvent sous-estimer le nombre de géniteurs requis pour atteindre des objectifs comme le rendement maximal soutenu ou des cibles pour la production d’alevins [@Staton2021]. Certains de ces changements ont été observés chez les saumons rouges des rivières Skeena et Nass, et une analyse plus détaillée est nécessaire pour évaluer s’ils représenteront probablement des changements importants dans le recrutement qui devront être pris en compte dans les objectifs de gestion de ces stocks. Il faudra peut-être envisager d’autres approches pour intégrer les changements démographiques dans l’échappée, comme tenir compte des objectifs d’échappée fondés sur la production d’œufs plutôt que sur l’abondance des géniteurs, ou intégrer explicitement les changements démographiques dans la modélisation des géniteurs-recrues, comme les autres ajustements des objectifs d’échappée explorés dans @Connorsetal2022  pour le saumon chinook du Yukon.














